### ISSUE TITLE
how atom shared between verticle instance?

### ISSUE THREAD

**Issue by jianglibo** [vert-x/mod-lang-clojure#129]
####verticle for test
```
(def an-atom (atom 0))

(swap! an-atom + 1)
(swap! an-atom + 1)

(eb/send "test.data" @an-atom)
```
####test file
```
(defn test-deploy []
  (let [tms (atom 0)
        instances 10] 
    (eb/on-message "test.data"
                   (fn [m]
                     (swap! tms + 1)
                     (log/info (str "auto value is: " m))
                     (when (= instances @tms)
                       (tt/assert= (* instances 2) m)
                       (tt/test-complete))))
  (core/deploy-verticle "cn/intellijoy/clojure/atom_verticle.clj"
                        :instances instances
                        :handler (fn [err deploy-id]
                                   (tt/assert-nil err) ))))

```
test failed.

the log in console:
```
INFO: auto value is: 2
INFO: auto value is: 1
INFO: auto value is: 3
INFO: auto value is: 2
INFO: auto value is: 0
INFO: auto value is: 2
INFO: auto value is: 4
INFO: auto value is: 2
INFO: auto value is: 4
INFO: auto value is: 4
```

the result is random, is this mean use atom in file scope is a wrong? and why?

**Comment by tobias** [comment]
The reason why your test fails is because you are creating the atom var with `def`, so it is getting recreated for each of the 10 verticle instances, since each instance loads `atom_verticle.clj`. Depending on the timing of those loads, you will see what appears to be random values in the atom when it is actually being recreated randomly. The fix would be to use `defonce` instead of `def` to define the var.

Note, however, that the atom is only shared between the verticle instances because you are deploying from within an existing clojure runtime, so the verticle instances are all inheriting and sharing that runtime. If you deploy the same verticle from the `vertx` command, each verticle instance would have its own clojure runtime, and would therefore have it's own version of the atom.

The reason the verticle instances share a clojure runtime when deployed from clojure is the nature of clojure makes it impossible to create isolated runtimes from within a clojure runtime.

**Comment by jianglibo** [comment]
I see. thank you. I learn a lot.
