### ISSUE TITLE
how shutdown and restart http embedded server?

### ISSUE THREAD

**Issue by cocodrino** [vert-x/mod-lang-clojure#133]
Hi..I'm curious if it's possible shutdown and/or restart my server similar to how ring does..I'm running my app in the repl and just now I need restart my repl session with every change...

2) I've a cluster app and I wish than my embedded vertx app can communicate wit it using the event bus, is it possible?...how I configure my embedded app for join to my cluster??...
thank!...

**Comment by tobias** [comment]
If you are making changes to the http handler function and want the new versions to be used on the next request, you can pass the var for the handler function instead of the symbol, like so:

```clojure
(-> (http/server)
    (http/on-request #'request-handler) ;; notice the var-quote
    (http/listen 8080 "localhost")) 
```

That will cause the version of the handler function that is defined at request time to be used instead of the version defined when `on-request` is called. This is what the ring lein plugin does to provide this functionality.

Another option is to create `start` and `stop` functions for starting and stopping the web server, and define a reset fn: `(defn reset [] (stop) (start))`. You can then call `reset` from the repl.

To participate in a cluster, you'll need to pass a cluster host and port to listen on to `vertx.embed/vertx`, and you /may/ need to add `-Dvertx.clusterManagerFactory=org.vertx.java.spi.cluster.impl.hazelcast.HazelcastClusterManagerFactory` when you start the app.

**Comment by cocodrino** [comment]
thanks tobias, coming from scala I didnt expect than it was so simple, works perfect, but I've preferred use the vertx ring adapter instead of vertx directly ...

just now the only problem than I've is related to core async, If I need handle responses from my channel inside the ring handler I've troubles, 

(defn slow-request-handler [a]
  (!/go
    (while true
      ({:status 200 :body (!/<! (some-slow-request-here "xxx"))}))))

the response is a multichannel because it's wrapped by the go...I cant found an elegant way of solve it (write the #'compojure.response/Renderable protocol for multichannel would be enought?)

here is a solution than I think could be adapter to the vertx/ring adapter

https://github.com/ninjudd/ring-async

**Comment by tobias** [comment]
I believe the `ring-vertx-adapter` currently blocks waiting for each request to finish, which isn't the best solution. I think it could probably be adapted to use ring's new async support, similarly to ninjudd/ring-async. I don't do much with vertx these days, but @stream1984 may be open to changes to the ring adapter to make it more async.

**Comment by cocodrino** [comment]
thanks tobias, without async support that ring adapter seems a bit useless...here is other interesting project, Ill check it but would be cool than a clojure contributor check this out.

**Comment by cocodrino** [comment]
https://github.com/dgrnbrg/spiral

**Comment by stream1984** [comment]
Well, i have to spent time to our project as it at the crucial stage, i am glad someone is interesting to ring adapter, i would make a research if have free time or you can also make PR :)
